# ----------------------
#  NATIONS EVENT CONFIG
# ----------------------


# Features toggle
feature-meat-player-death: true
#feature-item-team-color: true

# Teams
teams:
  red:
    name: "Team Red"
    color-code: "c"
    permission: "group.red"
  blue:
    name: "Team Blue"
    color-code: "9"
    permission: "group.blue"


# Team core feature (NG1)
team-core-enable: true
team-core-world: "nations_ng1_world"
team-cores:
  core-red:
    name: "§c§lRED CORE"
    permission: "group.red"
    location:
      x: 0
      y: 79
      z: 100

  core-blue:
    name: "§9§lBLUE CORE"
    permission: "group.blue"
    location:
      x: 0
      y: 79
      z: -100
