# ----------------------
#  NATIONS EVENT CONFIG
# ----------------------


# Features toggle
feature-meat-player-death: true


# Teams
teams:
  team1:
    name: "Team One"
    color-code: "a"
    permission: "nationsevent.team.one"
  team2:
    name: "Team Two"
    color-code: "b"
    permission: "nationsevent.team.two"


# Team core feature (NG1)
team-core-enable: true
team-core-world: "world"
team-cores:
  core-red:
    name: "§c§lRED CORE"
    permission: "nationsevent.team.red"
    location:
      x: -597
      y: 69
      z: 2588

  core-blue:
    name: "§9§lBLUE CORE"
    permission: "nationsevent.team.blue"
    location:
      x: -599
      y: 69
      z: 2588
