# ----------------------
#  NATIONS EVENT CONFIG
# ----------------------


# Features toggle
feature-meat-player-death: true
#feature-item-team-color: true

# Teams
teams:
  red:
    name: "Team Cop"
    color-code: "9"
    permission: "nationsevent.team.cop"
  blue:
    name: "Team Robber"
    color-code: "f"
    permission: "nationsevent.team.robber"