# ----------------------
#  NATIONS EVENT CONFIG
# ----------------------


# Teams
teams:
  team1:
    name: "Team One"
    color-code: "a"
    permission: "team.one"
  team2:
    name: "Team Two"
    color-code: "b"
    permission: "team.two"


# Team core feature (NG1)
team-core-enable: true
team-core-world: "world"
team-cores:
  core1:
    name: "Core One"
    location: ""
    permission: "team.one"
  core2:
    name: "Core Two"
    location: ""
    permission: "team.two"