# ----------------------
#  NATIONS EVENT CONFIG
# ----------------------


# Features toggle
feature-meat-player-death: true


# Teams
teams:
  team1:
    name: "Team One"
    color-code: "a"
    permission: "group.team1"
  team2:
    name: "Team Two"
    color-code: "b"
    permission: "group.team2"


# Team core feature (NG1)
team-core-enable: true
team-core-world: "world"
team-cores:
  core-red:
    name: "§c§lRED CORE"
    permission: "group.team-red"
    location:
      x: 1
      y: 74
      z: 0

  core-blue:
    name: "§9§lBLUE CORE"
    permission: "group.team-blue"
    location:
      x: 3
      y: 74
      z: 0
