# ----------------------
#  NATIONS EVENT CONFIG
# ----------------------


# == Features toggle ==================================================================================================
# Make players drop meet on death
feature-meat-player-death: false
iron-door: true

# == Patches ==========================================================================================================
# Provent players from block glitching
patch-anti-block-glitching: true

# Provent players from using ender pearls
patch-anti-ender-pearl: true


# == Teams ============================================================================================================
teams:
  red:
    name: "Team Cop"
    color-code: "9"
    permission: "nationsevent.team.cop"
  blue:
    name: "Team Robber"
    color-code: "f"
    permission: "nationsevent.team.robber"


# == NG3 ==============================================================================================================
ng3-prison-location:
  x: -244
  y: 74
  z: -1253