name: NationsEvent
version: '${project.version}'
authors: [jjkay03]
website: https://jjkay03.com/

main: com.jjkay03.nationsevent.NationsEvent
api-version: '1.20'

commands:
  joinvc:
    permission: nationsevent.command.joinvc
    permission-message: "You do not have permission to use this command"

  announcesession:
    permission: nationsevent.command.announcesession
    permission-message: "You do not have permission to use this command"

  sessiontime:
    permission: nationsevent.command.sessiontime
    permission-message: "You do not have permission to use this command"

  pvptoggle:
    permission: nationsevent.command.pvptoggle
    permission-message: "You do not have permission to use this command"

  pvpalerts:
    permission: nationsevent.command.pvpalerts
    permission-message: "You do not have permission to use this command"

#  teammessage:
#    aliases: ["teammsg", "tmessage", "tmsg","tm"]
#    permission: nationsevent.command.teammessage
#    permission-message: "You do not have permission to use this command"